table costos_ciclo
	lineageTag: ce4b6631-008c-45aa-a448-079ceb1f2574

	measure 'Consumo Ciclo m3_ha' =
			DIVIDE(
			    SUM('costos_ciclo'[volumen_agua_total_m3]),
			    CALCULATE(SUM('parcelas'[area_ha]))
			)
		formatString: #,##0.0

	measure 'Ciclos Sobre Meta' =
			CALCULATE(
			    COUNTROWS('costos_ciclo'),
			    FILTER(
			        'costos_ciclo',
			        DIVIDE('costos_ciclo'[volumen_agua_total_m3], RELATED('parcelas'[area_ha])) > 6000
			    )
			)
		formatString: #,##0

	measure 'Pct Ciclos Sobre Meta' =
			DIVIDE([Ciclos Sobre Meta], COUNTROWS('costos_ciclo'), 0)
		formatString: 0%

	column id_costo
		dataType: string
		lineageTag: 2e78e090-02e5-4302-91b7-b589e1a42b74
		summarizeBy: none
		sourceColumn: id_costo

		annotation SummarizationSetBy = Automatic

	column id_parcela
		dataType: string
		lineageTag: e569bfe1-637a-4dc3-8730-494c32eb2e75
		summarizeBy: none
		sourceColumn: id_parcela

		annotation SummarizationSetBy = Automatic

	column ciclo_agricola
		dataType: string
		lineageTag: 8be74b13-9b74-44f8-81d7-2e5071012842
		summarizeBy: none
		sourceColumn: ciclo_agricola

		annotation SummarizationSetBy = Automatic

	column cultivo
		dataType: string
		lineageTag: 20bf1c16-ec07-47cb-a636-18095d996e75
		summarizeBy: none
		sourceColumn: cultivo

		annotation SummarizationSetBy = Automatic

	column volumen_agua_total_m3
		dataType: double
		lineageTag: 6c79cd75-6ca2-4326-b1a0-99103f036138
		summarizeBy: sum
		sourceColumn: volumen_agua_total_m3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column costo_agua_mxn
		dataType: double
		lineageTag: 186bfcac-31db-4e9d-a470-7cb02c5bc8c8
		summarizeBy: sum
		sourceColumn: costo_agua_mxn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column costo_fertilizantes_mxn
		dataType: double
		lineageTag: 4467ea6b-6aa4-4b29-a1b8-0b1ccd95bde8
		summarizeBy: sum
		sourceColumn: costo_fertilizantes_mxn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column costo_agroquimicos_mxn
		dataType: double
		lineageTag: 7f145cfb-3f3b-45c6-af4b-2b9b0345f98d
		summarizeBy: sum
		sourceColumn: costo_agroquimicos_mxn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column costo_semilla_mxn
		dataType: double
		lineageTag: eedd27f5-a991-46dd-a413-8590c2fec84d
		summarizeBy: sum
		sourceColumn: costo_semilla_mxn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column costo_maquinaria_mxn
		dataType: double
		lineageTag: 7d1d70a4-ac40-4735-ba56-aed9c21a2a2d
		summarizeBy: sum
		sourceColumn: costo_maquinaria_mxn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column costo_mano_obra_mxn
		dataType: double
		lineageTag: 1cc09c00-8012-48b3-a7d2-7e9648ab89a0
		summarizeBy: sum
		sourceColumn: costo_mano_obra_mxn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ingreso_estimado_mxn
		dataType: double
		lineageTag: acfee0d9-e423-4828-b948-44427ae971c3
		summarizeBy: sum
		sourceColumn: ingreso_estimado_mxn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column margen_contribucion_mxn
		dataType: double
		lineageTag: 72e5b465-c680-4697-b2e4-38de7468559c
		summarizeBy: sum
		sourceColumn: margen_contribucion_mxn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition costos_ciclo = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents("C:\Users\madri\Downloads\pp26(Omar)\synthetic\costos_ciclo.csv"),[Delimiter=",", Columns=13, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"id_costo", type text}, {"id_parcela", type text}, {"ciclo_agricola", type text}, {"cultivo", type text}, {"volumen_agua_total_m3", type number}, {"costo_agua_mxn", type number}, {"costo_fertilizantes_mxn", type number}, {"costo_agroquimicos_mxn", type number}, {"costo_semilla_mxn", type number}, {"costo_maquinaria_mxn", type number}, {"costo_mano_obra_mxn", type number}, {"ingreso_estimado_mxn", type number}, {"margen_contribucion_mxn", type number}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

