table cultivos_catalogo
	lineageTag: 909a4173-d290-494c-9935-c2459bf6d812

	column id_cultivo
		dataType: string
		lineageTag: cf0d919d-1ca2-45f4-922a-d9a2524a5fbb
		summarizeBy: none
		sourceColumn: id_cultivo

		annotation SummarizationSetBy = Automatic

	column nombre_comun
		dataType: string
		lineageTag: c96009b9-8e0c-422c-afc5-0b470faecd23
		summarizeBy: none
		sourceColumn: nombre_comun

		annotation SummarizationSetBy = Automatic

	column nombre_cientifico
		dataType: string
		lineageTag: 8729662e-9052-45d3-aa17-69cb3c3bc977
		summarizeBy: none
		sourceColumn: nombre_cientifico

		annotation SummarizationSetBy = Automatic

	column kc_inicial
		dataType: double
		lineageTag: 9a6db6b3-03aa-4ae7-b3f5-5d3c71905fe6
		summarizeBy: none
		sourceColumn: kc_inicial

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column kc_medio
		dataType: double
		lineageTag: 4bf7da07-e12d-4590-8dbd-bdadef465317
		summarizeBy: none
		sourceColumn: kc_medio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column kc_final
		dataType: double
		lineageTag: c566304a-ccf4-4a80-8be0-b3c9ccc34ff1
		summarizeBy: none
		sourceColumn: kc_final

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ky_total
		dataType: double
		lineageTag: f2006176-0331-4cc4-8007-126e0d565138
		summarizeBy: none
		sourceColumn: ky_total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column dias_etapa_inicial
		dataType: int64
		formatString: 0
		lineageTag: 78179e5a-d9ea-46ca-a105-7faa75f39065
		summarizeBy: none
		sourceColumn: dias_etapa_inicial

		annotation SummarizationSetBy = Automatic

	column dias_etapa_desarrollo
		dataType: int64
		formatString: 0
		lineageTag: 17c65f50-bf9e-4f02-a222-a14efd33332b
		summarizeBy: none
		sourceColumn: dias_etapa_desarrollo

		annotation SummarizationSetBy = Automatic

	column dias_etapa_media
		dataType: int64
		formatString: 0
		lineageTag: 0c8a3841-dd53-450e-8f6f-050718a9a848
		summarizeBy: none
		sourceColumn: dias_etapa_media

		annotation SummarizationSetBy = Automatic

	column dias_etapa_final
		dataType: int64
		formatString: 0
		lineageTag: b175b399-144e-4765-84d8-23f9281c2a90
		summarizeBy: none
		sourceColumn: dias_etapa_final

		annotation SummarizationSetBy = Automatic

	column rendimiento_potencial_ton
		dataType: double
		lineageTag: 084807f9-9082-48c2-b1d9-33c56bcab6e0
		summarizeBy: none
		sourceColumn: rendimiento_potencial_ton

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition cultivos_catalogo = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents("C:\Users\madri\Downloads\pp26(Omar)\synthetic\cultivos_catalogo.csv"),[Delimiter=",", Columns=12, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"id_cultivo", type text}, {"nombre_comun", type text}, {"nombre_cientifico", type text}, {"kc_inicial", type number}, {"kc_medio", type number}, {"kc_final", type number}, {"ky_total", type number}, {"dias_etapa_inicial", Int64.Type}, {"dias_etapa_desarrollo", Int64.Type}, {"dias_etapa_media", Int64.Type}, {"dias_etapa_final", Int64.Type}, {"rendimiento_potencial_ton", type number}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

