table historial_riego
	lineageTag: 1c2e9b24-511e-4543-8b77-fab08bd0421f

	measure 'Consumo Agua m3_ha' =
			CALCULATE(
			    AVERAGE('historial_riego'[volumen_m3_ha]),
			    'historial_riego'[ciclo_agricola] = MAX('historial_riego'[ciclo_agricola])
			)
		formatString: #,##0

	measure 'Linea Base m3_ha' = 8000
		formatString: #,##0

	measure 'Objetivo m3_ha' = 6000
		formatString: #,##0

	measure 'Tarifa MXN_m3' = 1.68
		formatString: #,##0.00

	measure 'Ahorro m3_ha' = [Linea Base m3_ha] - [Consumo Agua m3_ha]
		formatString: #,##0

	measure 'Ahorro Costo MXN_ha' = [Ahorro m3_ha] * [Tarifa MXN_m3]
		formatString: $#,##0

	measure 'Pct Ahorro' = DIVIDE([Ahorro m3_ha], [Linea Base m3_ha], 0)
		formatString: 0%

	measure 'Total Agua Aplicada m3' =
			SUMX(
			    'historial_riego',
			    'historial_riego'[volumen_m3_ha] * RELATED('parcelas'[area_ha])
			)
		formatString: #,##0

	measure 'Costo Total Energia MXN' = SUM('historial_riego'[costo_energia_mxn])
		formatString: $#,##0

	measure 'Eventos Sobre Meta' =
			COUNTROWS(
			    FILTER('historial_riego', 'historial_riego'[volumen_m3_ha] > 6500)
			)
		formatString: #,##0

	measure 'Consumo Promedio por Metodo' = AVERAGE('historial_riego'[volumen_m3_ha])
		formatString: #,##0

	column id_riego
		dataType: string
		lineageTag: b2a17623-b101-42fe-b949-124bc066fbec
		summarizeBy: none
		sourceColumn: id_riego

		annotation SummarizationSetBy = Automatic

	column id_parcela
		dataType: string
		lineageTag: 3573891f-3255-40ad-a2a3-a6a1f4810ecd
		summarizeBy: none
		sourceColumn: id_parcela

		annotation SummarizationSetBy = Automatic

	column ciclo_agricola
		dataType: string
		lineageTag: 55507c07-f33b-45c0-9bac-850147ffad16
		summarizeBy: none
		sourceColumn: ciclo_agricola

		annotation SummarizationSetBy = Automatic

	column id_recomendacion
		dataType: string
		lineageTag: e437dfd5-f09f-41fe-8ab5-3df9ebdc4e49
		summarizeBy: none
		sourceColumn: id_recomendacion

		annotation SummarizationSetBy = Automatic

	column fecha_riego
		dataType: dateTime
		formatString: Long Date
		lineageTag: b9ac964e-666d-4a08-8eaf-94048323feee
		summarizeBy: none
		sourceColumn: fecha_riego

		variation Variación
			isDefault
			relationship: 9046af33-6786-4a4e-b47b-2833c76017aa
			defaultHierarchy: LocalDateTable_f6be6a53-4a30-485a-b7f8-f22626d706f7.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column volumen_m3_ha
		dataType: double
		lineageTag: a2c2ebde-cae0-4f2c-becd-4a98bbfcf561
		summarizeBy: sum
		sourceColumn: volumen_m3_ha

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column lamina_mm
		dataType: double
		lineageTag: 8ed02592-b573-4ab4-9821-e95ea7376161
		summarizeBy: sum
		sourceColumn: lamina_mm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column duracion_horas
		dataType: double
		lineageTag: d828ebd4-bf9d-4555-a497-b3bec7bbaa8c
		summarizeBy: sum
		sourceColumn: duracion_horas

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column metodo_riego
		dataType: string
		lineageTag: b637685e-62ea-4675-819b-c7097553a527
		summarizeBy: none
		sourceColumn: metodo_riego

		annotation SummarizationSetBy = Automatic

	column origen_decision
		dataType: string
		lineageTag: 685d5333-e4e5-403a-b627-2d4c1c09dd15
		summarizeBy: none
		sourceColumn: origen_decision

		annotation SummarizationSetBy = Automatic

	column costo_energia_mxn
		dataType: double
		lineageTag: 9b151357-55c1-4dff-b74d-d66a15dee183
		summarizeBy: sum
		sourceColumn: costo_energia_mxn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ciclo_vol_target_m3_ha
		dataType: double
		lineageTag: 1e6d2abf-629b-47cb-ac32-0e57beb80d68
		summarizeBy: sum
		sourceColumn: ciclo_vol_target_m3_ha

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column observaciones
		dataType: string
		lineageTag: cc6c3aa2-ce9c-4863-8272-0b77345dfc26
		summarizeBy: none
		sourceColumn: observaciones

		annotation SummarizationSetBy = Automatic

	column created_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 8d6ea451-8247-4974-aea2-337350f7e58e
		summarizeBy: none
		sourceColumn: created_at

		variation Variación
			isDefault
			relationship: bcfb0f0b-7fb5-4acf-8f2f-d92ef2daafd3
			defaultHierarchy: LocalDateTable_51813e69-7b9b-4b45-ae83-c04588559fe6.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	partition historial_riego = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents("C:\Users\madri\Downloads\pp26(Omar)\synthetic\historial_riego.csv"),[Delimiter=",", Columns=14, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"id_riego", type text}, {"id_parcela", type text}, {"ciclo_agricola", type text}, {"id_recomendacion", type text}, {"fecha_riego", type date}, {"volumen_m3_ha", type number}, {"lamina_mm", type number}, {"duracion_horas", type number}, {"metodo_riego", type text}, {"origen_decision", type text}, {"costo_energia_mxn", type number}, {"ciclo_vol_target_m3_ha", type number}, {"observaciones", type text}, {"created_at", type datetime}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

