table recomendaciones
	lineageTag: 3479a0d0-403d-4f75-b1ff-d332a6b63e1c

	measure 'Tasa Adopcion Pct' =
			DIVIDE(
			    COUNTROWS(FILTER('recomendaciones', 'recomendaciones'[aceptada] = "aceptada")),
			    COUNTROWS('recomendaciones'),
			    0
			)
		formatString: 0%

	measure 'Total Recomendaciones' = COUNTROWS('recomendaciones')
		formatString: #,##0

	measure 'Rec Aceptadas' = COUNTROWS(FILTER('recomendaciones', 'recomendaciones'[aceptada] = "aceptada"))
		formatString: #,##0

	measure 'Rec Pendientes' = COUNTROWS(FILTER('recomendaciones', 'recomendaciones'[aceptada] = "pendiente"))
		formatString: #,##0

	measure 'Rec Ignoradas' = COUNTROWS(FILTER('recomendaciones', 'recomendaciones'[aceptada] = "ignorada"))
		formatString: #,##0

	measure 'ETc Promedio mm' = AVERAGE('recomendaciones'[etc_calculada])
		formatString: #,##0.0

	measure 'ETo Promedio' = AVERAGE('recomendaciones'[eto_referencia])
		formatString: #,##0.0

	measure 'Deficit Acumulado Promedio' = AVERAGE('recomendaciones'[deficit_acumulado_mm])
		formatString: #,##0.0

	measure 'Pct Urgencia Critica' =
			DIVIDE(
			    COUNTROWS(FILTER('recomendaciones', 'recomendaciones'[nivel_urgencia] = "critico")),
			    COUNTROWS('recomendaciones'),
			    0
			)
		formatString: 0%

	column id_recomendacion
		dataType: string
		lineageTag: 44aac02d-5365-4ef4-a59e-2ae250d26d3f
		summarizeBy: none
		sourceColumn: id_recomendacion

		annotation SummarizationSetBy = Automatic

	column id_parcela
		dataType: string
		lineageTag: b7cb1276-3a8c-46d4-9760-c0c9b0c22f85
		summarizeBy: none
		sourceColumn: id_parcela

		annotation SummarizationSetBy = Automatic

	column id_cultivo
		dataType: string
		lineageTag: 7510ae85-1249-4e44-981d-b65e75b87b81
		summarizeBy: none
		sourceColumn: id_cultivo

		annotation SummarizationSetBy = Automatic

	column fecha_generacion
		dataType: dateTime
		formatString: General Date
		lineageTag: aa9e81da-a9d0-40ab-a201-9c272f03dba2
		summarizeBy: none
		sourceColumn: fecha_generacion

		variation Variación
			isDefault
			relationship: 9705323c-22b3-4361-9da2-93c55371d2e9
			defaultHierarchy: LocalDateTable_bee683ef-3c81-42b7-9ab9-c5486a4bd479.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column fecha_riego_sugerida
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1fee903e-d074-4585-8ce6-51cf17cbd42f
		summarizeBy: none
		sourceColumn: fecha_riego_sugerida

		variation Variación
			isDefault
			relationship: 8379e603-3864-4402-a863-2080a424ff57
			defaultHierarchy: LocalDateTable_4c15115a-ef08-4705-873b-c65689748cc9.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column lamina_recomendada_mm
		dataType: double
		lineageTag: dea501b5-3522-4701-aa36-b63cf9d9eea8
		summarizeBy: sum
		sourceColumn: lamina_recomendada_mm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column eto_referencia
		dataType: double
		lineageTag: fb935c68-a531-45e9-a03e-83fae8a093d0
		summarizeBy: sum
		sourceColumn: eto_referencia

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column etc_calculada
		dataType: double
		lineageTag: 2a352cf3-e836-46db-b407-efcc5b16ad51
		summarizeBy: sum
		sourceColumn: etc_calculada

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column deficit_acumulado_mm
		dataType: double
		lineageTag: 5137fdb8-5a56-4de9-a470-e8a5f62ae115
		summarizeBy: sum
		sourceColumn: deficit_acumulado_mm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column dias_sin_riego
		dataType: int64
		formatString: 0
		lineageTag: db834950-e6ad-4c81-9d79-24be6af96b13
		summarizeBy: sum
		sourceColumn: dias_sin_riego

		annotation SummarizationSetBy = Automatic

	column nivel_urgencia
		dataType: string
		lineageTag: 480ffc3a-d0f8-49f5-89f8-8e7d02fa638b
		summarizeBy: none
		sourceColumn: nivel_urgencia

		annotation SummarizationSetBy = Automatic

	column algoritmo_version
		dataType: string
		lineageTag: 761b5fca-5aac-4bcc-98f5-193946124938
		summarizeBy: none
		sourceColumn: algoritmo_version

		annotation SummarizationSetBy = Automatic

	column aceptada
		dataType: string
		lineageTag: b5c9d411-6813-470b-aabe-9d7ac9bedafa
		summarizeBy: none
		sourceColumn: aceptada

		annotation SummarizationSetBy = Automatic

	column lamina_ejecutada_mm
		dataType: double
		lineageTag: a1f686b2-c2ec-4098-b723-5fcd024509ae
		summarizeBy: sum
		sourceColumn: lamina_ejecutada_mm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column parametros_json
		dataType: string
		lineageTag: c00fdcbb-31f6-406e-bf46-7b9582e117a9
		summarizeBy: none
		sourceColumn: parametros_json

		annotation SummarizationSetBy = Automatic

	partition recomendaciones = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents("C:\Users\madri\Downloads\pp26(Omar)\synthetic\recomendaciones.csv"),[Delimiter=",", Columns=15, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"id_recomendacion", type text}, {"id_parcela", type text}, {"id_cultivo", type text}, {"fecha_generacion", type datetime}, {"fecha_riego_sugerida", type date}, {"lamina_recomendada_mm", type number}, {"eto_referencia", type number}, {"etc_calculada", type number}, {"deficit_acumulado_mm", type number}, {"dias_sin_riego", Int64.Type}, {"nivel_urgencia", type text}, {"algoritmo_version", type text}, {"aceptada", type text}, {"lamina_ejecutada_mm", type number}, {"parametros_json", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

