table cultivos_catalogo
	lineageTag: 82104a10-f961-4c8f-99c4-22dc9daf3a35

	column id_cultivo
		dataType: string
		lineageTag: 2e55456a-073d-4648-8d89-8d7c84811e1c
		summarizeBy: none
		sourceColumn: id_cultivo

		annotation SummarizationSetBy = Automatic

	column nombre_comun
		dataType: string
		lineageTag: 190d87bb-ea43-4eca-9243-1e45fc1fbeb6
		summarizeBy: none
		sourceColumn: nombre_comun

		annotation SummarizationSetBy = Automatic

	column nombre_cientifico
		dataType: string
		lineageTag: 11d0522b-29f6-4824-8aac-997aa0db309c
		summarizeBy: none
		sourceColumn: nombre_cientifico

		annotation SummarizationSetBy = Automatic

	column kc_inicial
		dataType: double
		lineageTag: 1fc4edf1-86a6-47bd-9773-454dc207dcb9
		summarizeBy: none
		sourceColumn: kc_inicial

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column kc_medio
		dataType: double
		lineageTag: 2ab8ffa4-8731-4f78-ab27-44401f1eb503
		summarizeBy: none
		sourceColumn: kc_medio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column kc_final
		dataType: double
		lineageTag: 9757e8e1-b6a2-47bf-bfe5-481c725833a2
		summarizeBy: none
		sourceColumn: kc_final

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ky_total
		dataType: double
		lineageTag: 672e577c-2e04-41d6-9ddc-0d2bbe5cfe40
		summarizeBy: none
		sourceColumn: ky_total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column dias_etapa_inicial
		dataType: int64
		formatString: 0
		lineageTag: 8a92fc22-6122-4981-86d2-f58ad44eb18b
		summarizeBy: none
		sourceColumn: dias_etapa_inicial

		annotation SummarizationSetBy = Automatic

	column dias_etapa_desarrollo
		dataType: int64
		formatString: 0
		lineageTag: ecbaab61-3029-45cd-b6c9-38da1221cc1e
		summarizeBy: none
		sourceColumn: dias_etapa_desarrollo

		annotation SummarizationSetBy = Automatic

	column dias_etapa_media
		dataType: int64
		formatString: 0
		lineageTag: 971eb55d-3020-4ac6-b0ba-c947c65f1acd
		summarizeBy: none
		sourceColumn: dias_etapa_media

		annotation SummarizationSetBy = Automatic

	column dias_etapa_final
		dataType: int64
		formatString: 0
		lineageTag: f7c365ab-7b2c-4b7f-af6e-087a41f0c0ea
		summarizeBy: none
		sourceColumn: dias_etapa_final

		annotation SummarizationSetBy = Automatic

	column rendimiento_potencial_ton
		dataType: double
		lineageTag: 8fa148b6-4714-403d-b70c-f6d2b78cd622
		summarizeBy: none
		sourceColumn: rendimiento_potencial_ton

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition cultivos_catalogo = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents("C:\Users\madri\Downloads\pp26(Omar)\data\synthetic\cultivos_catalogo.csv"),[Delimiter=",", Columns=12, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"id_cultivo", type text}, {"nombre_comun", type text}, {"nombre_cientifico", type text}, {"kc_inicial", type number}, {"kc_medio", type number}, {"kc_final", type number}, {"ky_total", type number}, {"dias_etapa_inicial", Int64.Type}, {"dias_etapa_desarrollo", Int64.Type}, {"dias_etapa_media", Int64.Type}, {"dias_etapa_final", Int64.Type}, {"rendimiento_potencial_ton", type number}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

