table recomendaciones
	lineageTag: 4abd8c37-4f87-4b7f-8e3f-391d1e2cd99f

	column id_recomendacion
		dataType: string
		lineageTag: 265c4554-8c61-4343-8b8b-33a9aa6df787
		summarizeBy: none
		sourceColumn: id_recomendacion

		annotation SummarizationSetBy = Automatic

	column id_parcela
		dataType: string
		lineageTag: dfec6dc1-aa20-4aef-9339-6a75473e8056
		summarizeBy: none
		sourceColumn: id_parcela

		annotation SummarizationSetBy = Automatic

	column id_cultivo
		dataType: string
		lineageTag: 3a7cfe17-1d41-4fe8-9eae-418a9e67307d
		summarizeBy: none
		sourceColumn: id_cultivo

		annotation SummarizationSetBy = Automatic

	column fecha_generacion
		dataType: dateTime
		formatString: General Date
		lineageTag: bfdf5df6-6eac-4b10-a15b-bc646d9f0e8d
		summarizeBy: none
		sourceColumn: fecha_generacion

		variation Variación
			isDefault
			relationship: 00889589-418a-4dca-98e9-384e3a9754a3
			defaultHierarchy: LocalDateTable_14c46fbf-e64f-4810-a21a-eaa890852f3a.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column fecha_riego_sugerida
		dataType: dateTime
		formatString: Long Date
		lineageTag: dafbad29-f227-45e6-93ab-001ebb4fdc5b
		summarizeBy: none
		sourceColumn: fecha_riego_sugerida

		variation Variación
			isDefault
			relationship: dfb9135b-689a-4ae5-a72d-1a4873d5d7f3
			defaultHierarchy: LocalDateTable_c95ae0a6-13a5-4407-a9b4-08601697a43e.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column lamina_recomendada_mm
		dataType: double
		lineageTag: 4cab8fd4-bcac-44ad-9782-73605f0e2ed9
		summarizeBy: sum
		sourceColumn: lamina_recomendada_mm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column eto_referencia
		dataType: double
		lineageTag: f404d0ba-fc43-44e6-9c2a-d4b24ed38ec5
		summarizeBy: sum
		sourceColumn: eto_referencia

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column etc_calculada
		dataType: double
		lineageTag: 9697027c-67c4-4b91-ac6a-5753b0c7d3de
		summarizeBy: none
		sourceColumn: etc_calculada

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column deficit_acumulado_mm
		dataType: double
		lineageTag: d9538c06-9dbd-4cf4-9fdb-96958f1a6d31
		summarizeBy: sum
		sourceColumn: deficit_acumulado_mm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column dias_sin_riego
		dataType: int64
		formatString: 0
		lineageTag: 4662b212-3795-40f1-a762-38a5bd898aa1
		summarizeBy: sum
		sourceColumn: dias_sin_riego

		annotation SummarizationSetBy = Automatic

	column nivel_urgencia
		dataType: string
		lineageTag: 785b9e9f-c135-43c3-bde3-0a010172bce2
		summarizeBy: none
		sourceColumn: nivel_urgencia

		annotation SummarizationSetBy = Automatic

	column algoritmo_version
		dataType: string
		lineageTag: 8c421ef7-7661-4d2a-b504-3a99c0da542c
		summarizeBy: none
		sourceColumn: algoritmo_version

		annotation SummarizationSetBy = Automatic

	column aceptada
		dataType: string
		lineageTag: 8e61c7c7-fc48-46e6-abba-d3439ee4fdcc
		summarizeBy: none
		sourceColumn: aceptada

		annotation SummarizationSetBy = Automatic

	column lamina_ejecutada_mm
		dataType: double
		lineageTag: 6c56ae0a-eb01-42fe-a47c-26541892d022
		summarizeBy: sum
		sourceColumn: lamina_ejecutada_mm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column parametros_json
		dataType: string
		lineageTag: 9322b5ac-dc49-4c6f-9d20-2c8a6ee1bf9e
		summarizeBy: none
		sourceColumn: parametros_json

		annotation SummarizationSetBy = Automatic

	partition recomendaciones = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents("C:\Users\madri\Downloads\pp26(Omar)\data\synthetic\recomendaciones.csv"),[Delimiter=",", Columns=15, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"id_recomendacion", type text}, {"id_parcela", type text}, {"id_cultivo", type text}, {"fecha_generacion", type datetime}, {"fecha_riego_sugerida", type date}, {"lamina_recomendada_mm", type number}, {"eto_referencia", type number}, {"etc_calculada", type number}, {"deficit_acumulado_mm", type number}, {"dias_sin_riego", Int64.Type}, {"nivel_urgencia", type text}, {"algoritmo_version", type text}, {"aceptada", type text}, {"lamina_ejecutada_mm", type number}, {"parametros_json", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

