table usuarios
	lineageTag: 00e3f185-703c-4fcb-aacf-4f9c096eb586

	column id_usuario
		dataType: string
		lineageTag: 09fe0d3b-f193-46d1-be91-94a9eac13331
		summarizeBy: none
		sourceColumn: id_usuario

		annotation SummarizationSetBy = Automatic

	column nombre_completo
		dataType: string
		lineageTag: 8147a238-f7a4-47ac-a7e7-53880f9932bc
		summarizeBy: none
		sourceColumn: nombre_completo

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: 4fb10e06-9cc9-4adf-80a2-2c949648a1dc
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	column telefono
		dataType: int64
		formatString: 0
		lineageTag: d096cb5d-4f0f-4a3d-979e-ab56760b6a6b
		summarizeBy: sum
		sourceColumn: telefono

		annotation SummarizationSetBy = Automatic

	column modulo_dr041
		dataType: string
		lineageTag: ce158fbf-448a-4c68-bd49-f9721caf766a
		summarizeBy: none
		sourceColumn: modulo_dr041

		annotation SummarizationSetBy = Automatic

	column activo
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 68a3930f-f164-4e68-87c4-45ab8950f0f0
		summarizeBy: none
		sourceColumn: activo

		annotation SummarizationSetBy = Automatic

	column created_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 91103249-6718-4f66-8e9d-15c9f4a3364c
		summarizeBy: none
		sourceColumn: created_at

		variation Variación
			isDefault
			relationship: fca7c6c9-e1f7-4233-b85e-c6d85bde9193
			defaultHierarchy: LocalDateTable_3819ea90-a117-4137-b162-eeb9d1e78752.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	partition usuarios = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents("C:\Users\madri\Downloads\pp26(Omar)\data\synthetic\usuarios.csv"),[Delimiter=",", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"id_usuario", type text}, {"nombre_completo", type text}, {"email", type text}, {"telefono", Int64.Type}, {"modulo_dr041", type text}, {"activo", type logical}, {"created_at", type datetime}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

