"""
Script temporal: agrega secciones 14 (Panel EDA) y 15 (Radar Calidad)
al notebook ml/experiments/eda_milpin.ipynb
"""
import json
from pathlib import Path

NB_PATH = Path(__file__).parent.parent / "ml" / "experiments" / "eda_milpin.ipynb"

with open(NB_PATH, "r", encoding="utf-8") as f:
    nb = json.load(f)


def md_cell(lines):
    return {"cell_type": "markdown", "metadata": {}, "source": lines}


def code_cell(lines):
    return {"cell_type": "code", "execution_count": None,
            "metadata": {}, "outputs": [], "source": lines}


# ══════════════════════════════════════════════════════════════════════════════
# SECCIÓN 14 — Panel EDA
# ══════════════════════════════════════════════════════════════════════════════
MD_14 = md_cell([
    "---\n",
    "## 14 · Panel EDA — Distribuciones y Correlaciones\n",
    "\n",
    "Panel de 6 gráficas que caracterizan el comportamiento climático\n",
    "del dataset sintético `milpin_ciclos_ml.csv` (Valle del Yaqui, 2021-2025):\n",
    "\n",
    "| # | Gráfica | Variable(s) |\n",
    "|---|---------|-------------|\n",
    "| 1 | Distribución ETo diaria por mes (violin) | `eto_acumulado_mm` |\n",
    "| 2 | Heatmap de correlaciones climáticas | todas numéricas |\n",
    "| 3 | Boxplot temperatura máxima por estación | `t_max_mean`, `estacion` |\n",
    "| 4 | Serie temporal ETo 2021-2025 | `fecha_siembra`, `eto_acumulado_mm` |\n",
    "| 5 | Dispersión T_max vs ETo | `t_max_mean`, `eto_acumulado_mm` |\n",
    "| 6 | Distribución humedad relativa | `hr_mean` |\n",
])

CODE_14 = code_cell([
    "# ══════════════════════════════════════════════════════════════════════════════\n",
    "# SECCIÓN 14 — Panel EDA: Distribuciones y Correlaciones\n",
    "# ══════════════════════════════════════════════════════════════════════════════\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.gridspec as gridspec\n",
    "import seaborn as sns\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from pathlib import Path\n",
    "\n",
    "# Cargar dataset\n",
    "DATA_PATH = Path(\"../../data/synthetic/milpin_ciclos_ml.csv\")\n",
    "if not DATA_PATH.exists():\n",
    "    DATA_PATH = Path(\"data/synthetic/milpin_ciclos_ml.csv\")\n",
    "\n",
    "df = pd.read_csv(DATA_PATH, parse_dates=[\"fecha_siembra\"], low_memory=False)\n",
    "\n",
    "CLIMA_COLS = [c for c in [\"eto_acumulado_mm\", \"t_max_mean\", \"t_min_mean\",\n",
    "                           \"hr_mean\", \"precipitacion_mm\", \"viento_m_s\"]\n",
    "              if c in df.columns]\n",
    "\n",
    "df[\"mes_siembra\"] = df[\"fecha_siembra\"].dt.month\n",
    "\n",
    "\n",
    "def _estacion(m):\n",
    "    if m in (12, 1, 2): return \"Invierno\"\n",
    "    if m in (3, 4, 5):  return \"Primavera\"\n",
    "    if m in (6, 7, 8):  return \"Verano\"\n",
    "    return \"Otoño\"\n",
    "\n",
    "\n",
    "df[\"estacion\"] = df[\"mes_siembra\"].map(_estacion)\n",
    "ORDEN_ESTACION = [\"Invierno\", \"Primavera\", \"Verano\", \"Otoño\"]\n",
    "\n",
    "# Layout 2x3\n",
    "fig = plt.figure(figsize=(20, 12))\n",
    "fig.patch.set_facecolor(\"#0d1117\")\n",
    "gs = gridspec.GridSpec(2, 3, figure=fig, hspace=0.45, wspace=0.35)\n",
    "\n",
    "ACCENT   = \"#00d4b4\"\n",
    "ACCENT2  = \"#f97316\"\n",
    "BG_AX    = \"#161b22\"\n",
    "GRID_CLR = \"#30363d\"\n",
    "TXT      = \"#e6edf3\"\n",
    "\n",
    "\n",
    "def _style_ax(ax, title):\n",
    "    ax.set_facecolor(BG_AX)\n",
    "    ax.tick_params(colors=TXT, labelsize=9)\n",
    "    for sp in ax.spines.values(): sp.set_edgecolor(GRID_CLR)\n",
    "    ax.xaxis.label.set_color(TXT)\n",
    "    ax.yaxis.label.set_color(TXT)\n",
    "    ax.set_title(title, color=TXT, fontsize=11, fontweight=\"bold\", pad=8)\n",
    "    ax.grid(color=GRID_CLR, linewidth=0.5, linestyle=\"--\", alpha=0.6)\n",
    "\n",
    "\n",
    "# 1. ETo por mes (violin)\n",
    "ax1 = fig.add_subplot(gs[0, 0])\n",
    "if \"eto_acumulado_mm\" in df.columns:\n",
    "    eto_mes = [df.loc[df[\"mes_siembra\"] == m, \"eto_acumulado_mm\"]\n",
    "               for m in range(1, 13)]\n",
    "    bp = ax1.violinplot(eto_mes, positions=range(1, 13),\n",
    "                        showmedians=True, widths=0.7)\n",
    "    for pc in bp[\"bodies\"]:\n",
    "        pc.set_facecolor(ACCENT); pc.set_alpha(0.6)\n",
    "    bp[\"cmedians\"].set_color(ACCENT2)\n",
    "    ax1.set_xlabel(\"Mes\"); ax1.set_ylabel(\"ETo acum. (mm)\")\n",
    "_style_ax(ax1, \"1 · ETo por Mes (violin)\")\n",
    "\n",
    "# 2. Heatmap correlaciones\n",
    "ax2 = fig.add_subplot(gs[0, 1])\n",
    "if len(CLIMA_COLS) >= 2:\n",
    "    corr = df[CLIMA_COLS].corr()\n",
    "    mask = np.triu(np.ones_like(corr, dtype=bool))\n",
    "    cmap = sns.diverging_palette(220, 20, as_cmap=True)\n",
    "    sns.heatmap(corr, mask=mask, cmap=cmap, center=0,\n",
    "                annot=True, fmt=\".2f\", linewidths=0.5,\n",
    "                linecolor=GRID_CLR, ax=ax2,\n",
    "                annot_kws={\"size\": 8, \"color\": TXT},\n",
    "                cbar_kws={\"shrink\": 0.8})\n",
    "    ax2.tick_params(axis=\"x\", rotation=30)\n",
    "_style_ax(ax2, \"2 · Correlaciones Climáticas\")\n",
    "\n",
    "# 3. Boxplot T_max por estación\n",
    "ax3 = fig.add_subplot(gs[0, 2])\n",
    "if \"t_max_mean\" in df.columns:\n",
    "    palette = {\"Invierno\": \"#38bdf8\", \"Primavera\": \"#4ade80\",\n",
    "               \"Verano\": ACCENT2, \"Otoño\": \"#a78bfa\"}\n",
    "    order = [e for e in ORDEN_ESTACION if e in df[\"estacion\"].unique()]\n",
    "    sns.boxplot(data=df, x=\"estacion\", y=\"t_max_mean\", order=order,\n",
    "                palette=palette, linewidth=1.2, fliersize=3, ax=ax3)\n",
    "    ax3.set_xlabel(\"\"); ax3.set_ylabel(\"T_max (°C)\")\n",
    "    ax3.tick_params(axis=\"x\", rotation=15)\n",
    "_style_ax(ax3, \"3 · T_max por Estación\")\n",
    "\n",
    "# 4. Serie temporal ETo\n",
    "ax4 = fig.add_subplot(gs[1, 0])\n",
    "if \"eto_acumulado_mm\" in df.columns:\n",
    "    ts = df.groupby(\"fecha_siembra\")[\"eto_acumulado_mm\"].mean().sort_index()\n",
    "    ts_roll = ts.rolling(30, min_periods=1).mean()\n",
    "    ax4.fill_between(ts.index, ts.values, alpha=0.2, color=ACCENT)\n",
    "    ax4.plot(ts.index, ts.values, color=ACCENT, linewidth=0.6, alpha=0.5)\n",
    "    ax4.plot(ts_roll.index, ts_roll.values, color=ACCENT2,\n",
    "             linewidth=1.8, label=\"Media móvil 30d\")\n",
    "    ax4.legend(fontsize=8, labelcolor=TXT, facecolor=BG_AX, edgecolor=GRID_CLR)\n",
    "    ax4.set_xlabel(\"Fecha\"); ax4.set_ylabel(\"ETo acum. (mm)\")\n",
    "_style_ax(ax4, \"4 · Serie Temporal ETo 2021-2025\")\n",
    "\n",
    "# 5. Scatter T_max vs ETo\n",
    "ax5 = fig.add_subplot(gs[1, 1])\n",
    "if {\"t_max_mean\", \"eto_acumulado_mm\"} <= set(df.columns):\n",
    "    sc = ax5.scatter(df[\"t_max_mean\"], df[\"eto_acumulado_mm\"],\n",
    "                     c=df[\"mes_siembra\"], cmap=\"plasma\",\n",
    "                     alpha=0.45, s=18, linewidths=0)\n",
    "    cb = fig.colorbar(sc, ax=ax5, shrink=0.8)\n",
    "    cb.set_label(\"Mes\", color=TXT, fontsize=8)\n",
    "    cb.ax.yaxis.set_tick_params(color=TXT)\n",
    "    plt.setp(cb.ax.yaxis.get_ticklabels(), color=TXT, fontsize=7)\n",
    "    valid = df[[\"t_max_mean\", \"eto_acumulado_mm\"]].dropna()\n",
    "    m_, b_ = np.polyfit(valid[\"t_max_mean\"], valid[\"eto_acumulado_mm\"], 1)\n",
    "    x_ = np.linspace(valid[\"t_max_mean\"].min(), valid[\"t_max_mean\"].max(), 100)\n",
    "    ax5.plot(x_, m_ * x_ + b_, color=ACCENT2, linewidth=1.5, linestyle=\"--\")\n",
    "    ax5.set_xlabel(\"T_max (°C)\"); ax5.set_ylabel(\"ETo acum. (mm)\")\n",
    "_style_ax(ax5, \"5 · T_max vs ETo (scatter)\")\n",
    "\n",
    "# 6. Distribución HR\n",
    "ax6 = fig.add_subplot(gs[1, 2])\n",
    "if \"hr_mean\" in df.columns:\n",
    "    ax6.hist(df[\"hr_mean\"].dropna(), bins=40,\n",
    "             color=ACCENT, edgecolor=BG_AX, linewidth=0.4, alpha=0.85)\n",
    "    mu, sigma = df[\"hr_mean\"].mean(), df[\"hr_mean\"].std()\n",
    "    ax6.axvline(mu, color=ACCENT2, linewidth=1.8, label=f\"Media: {mu:.1f}%\")\n",
    "    ax6.axvline(mu - sigma, color=\"#94a3b8\", linewidth=1,\n",
    "                linestyle=\":\", label=f\"\\u00b11\\u03c3: {sigma:.1f}\")\n",
    "    ax6.axvline(mu + sigma, color=\"#94a3b8\", linewidth=1, linestyle=\":\")\n",
    "    ax6.legend(fontsize=8, labelcolor=TXT, facecolor=BG_AX, edgecolor=GRID_CLR)\n",
    "    ax6.set_xlabel(\"HR media (%)\"); ax6.set_ylabel(\"Frecuencia\")\n",
    "_style_ax(ax6, \"6 · Distribución Humedad Relativa\")\n",
    "\n",
    "fig.suptitle(\n",
    "    \"MILP\\u00cdN \\u00b7 Panel EDA \\u2014 Variables Clim\\u00e1ticas Valle del Yaqui 2021-2025\",\n",
    "    color=TXT, fontsize=14, fontweight=\"bold\", y=1.01\n",
    ")\n",
    "plt.savefig(\"panel_eda_climatico.png\", dpi=150, bbox_inches=\"tight\",\n",
    "            facecolor=fig.get_facecolor())\n",
    "plt.show()\n",
    "print(\"Panel EDA guardado en panel_eda_climatico.png\")\n",
])

# ══════════════════════════════════════════════════════════════════════════════
# SECCIÓN 15 — Radar Calidad
# ══════════════════════════════════════════════════════════════════════════════
MD_15 = md_cell([
    "---\n",
    "## 15 · Gráfico Radar — Perfil de Calidad del Sistema\n",
    "\n",
    "Spider chart que compara el **estado actual** vs. el **objetivo MVP**\n",
    "en 7 dimensiones de calidad (ISO 25010 / RNF del proyecto).\n",
    "\n",
    "| Dimensión | Actual | MVP | Brecha |\n",
    "|-----------|--------|-----|--------|\n",
    "| Rendimiento | 3 | 4 | -1 |\n",
    "| Seguridad | 1 | 4 | **-3 ⚠ crítica** |\n",
    "| Disponibilidad | 2 | 4 | -2 |\n",
    "| Escalabilidad | 2 | 3 | -1 |\n",
    "| Mantenibilidad | 3 | 4 | -1 |\n",
    "| Usabilidad | 3 | 4 | -1 |\n",
    "| Precisión Agronómica | 4 | 5 | -1 |\n",
    "\n",
    "> **Brecha crítica — Seguridad (RNF-003/004):** credenciales en texto plano\n",
    "> (`.env` no ignorado), CORS abierto (`allow_origins=[\"*\"]`), path traversal\n",
    "> en `voice_endpoint.py`, y ausencia de autenticación real.  \n",
    "> Score actual: **1/5**. Objetivo MVP: **4/5**.\n",
])

CODE_15 = code_cell([
    "# ══════════════════════════════════════════════════════════════════════════════\n",
    "# SECCIÓN 15 — Gráfico Radar: Perfil de Calidad del Sistema\n",
    "# ══════════════════════════════════════════════════════════════════════════════\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.patches as mpatches\n",
    "import numpy as np\n",
    "\n",
    "DIMENSIONES = [\n",
    "    \"Rendimiento\",\n",
    "    \"Seguridad\",\n",
    "    \"Disponibilidad\",\n",
    "    \"Escalabilidad\",\n",
    "    \"Mantenibilidad\",\n",
    "    \"Usabilidad\",\n",
    "    \"Precisión\\nAgronómica\",\n",
    "]\n",
    "ACTUAL   = [3, 1, 2, 2, 3, 3, 4]\n",
    "OBJETIVO = [4, 4, 4, 3, 4, 4, 5]\n",
    "\n",
    "N = len(DIMENSIONES)\n",
    "angles   = np.linspace(0, 2 * np.pi, N, endpoint=False).tolist()\n",
    "angles  += angles[:1]\n",
    "actual   = ACTUAL   + ACTUAL[:1]\n",
    "objetivo = OBJETIVO + OBJETIVO[:1]\n",
    "\n",
    "BG       = \"#0d1117\"\n",
    "BG_AX    = \"#161b22\"\n",
    "GRID_CLR = \"#30363d\"\n",
    "TXT      = \"#e6edf3\"\n",
    "C_ACT    = \"#00d4b4\"\n",
    "C_OBJ    = \"#f97316\"\n",
    "C_ALERT  = \"#ef4444\"\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(9, 9),\n",
    "                       subplot_kw=dict(polar=True),\n",
    "                       facecolor=BG)\n",
    "ax.set_facecolor(BG_AX)\n",
    "\n",
    "# Anillos de referencia 1-5\n",
    "for level in range(1, 6):\n",
    "    ax.plot(angles, [level] * (N + 1), color=GRID_CLR,\n",
    "            linewidth=0.6, linestyle=\"--\", zorder=1)\n",
    "    ax.text(0, level + 0.08, str(level),\n",
    "            ha=\"center\", va=\"bottom\", fontsize=7.5, color=\"#8b949e\")\n",
    "\n",
    "# Radios\n",
    "for angle in angles[:-1]:\n",
    "    ax.plot([angle, angle], [0, 5], color=GRID_CLR, linewidth=0.8, zorder=1)\n",
    "\n",
    "# Polígono Objetivo\n",
    "ax.fill(angles, objetivo, color=C_OBJ, alpha=0.15, zorder=2)\n",
    "ax.plot(angles, objetivo, color=C_OBJ, linewidth=2.2,\n",
    "        linestyle=\"--\", label=\"Objetivo MVP\", zorder=3)\n",
    "ax.scatter(angles[:-1], OBJETIVO, color=C_OBJ, s=60, zorder=4)\n",
    "\n",
    "# Polígono Actual\n",
    "ax.fill(angles, actual, color=C_ACT, alpha=0.25, zorder=5)\n",
    "ax.plot(angles, actual, color=C_ACT, linewidth=2.5,\n",
    "        label=\"Estado actual\", zorder=6)\n",
    "ax.scatter(angles[:-1], ACTUAL, color=C_ACT, s=70, zorder=7)\n",
    "\n",
    "# Punto crítico Seguridad\n",
    "idx_seg = 1\n",
    "ax.scatter([angles[idx_seg]], [ACTUAL[idx_seg]],\n",
    "           color=C_ALERT, s=160, zorder=8,\n",
    "           edgecolors=\"white\", linewidths=1.5)\n",
    "ax.annotate(\n",
    "    \"⚠ RNF-003/004\\nBrecha: -3\",\n",
    "    xy=(angles[idx_seg], ACTUAL[idx_seg]),\n",
    "    xytext=(angles[idx_seg] + 0.35, ACTUAL[idx_seg] + 0.7),\n",
    "    color=C_ALERT, fontsize=8.5, fontweight=\"bold\",\n",
    "    arrowprops=dict(arrowstyle=\"->\", color=C_ALERT, lw=1.2),\n",
    "    zorder=9\n",
    ")\n",
    "\n",
    "# Etiquetas\n",
    "ax.set_xticks(angles[:-1])\n",
    "ax.set_xticklabels(DIMENSIONES, color=TXT, fontsize=10.5)\n",
    "ax.set_yticklabels([])\n",
    "ax.set_ylim(0, 5.4)\n",
    "ax.spines[\"polar\"].set_color(GRID_CLR)\n",
    "\n",
    "# Leyenda\n",
    "alert_patch = mpatches.Patch(color=C_ALERT, label=\"Brecha crítica (Seguridad)\")\n",
    "ax.legend(\n",
    "    handles=[\n",
    "        plt.Line2D([0], [0], color=C_ACT,  linewidth=2.5, label=\"Estado actual\"),\n",
    "        plt.Line2D([0], [0], color=C_OBJ,  linewidth=2.2,\n",
    "                   linestyle=\"--\", label=\"Objetivo MVP\"),\n",
    "        alert_patch,\n",
    "    ],\n",
    "    loc=\"upper right\", bbox_to_anchor=(1.35, 1.15),\n",
    "    facecolor=BG_AX, edgecolor=GRID_CLR, labelcolor=TXT, fontsize=10\n",
    ")\n",
    "\n",
    "fig.suptitle(\n",
    "    \"MILP\\u00cdN \\u00b7 Perfil de Calidad del Sistema\\n\"\n",
    "    \"Estado Actual vs. Objetivo MVP  (ISO 25010, escala 1\\u20135)\",\n",
    "    color=TXT, fontsize=13, fontweight=\"bold\", y=1.02\n",
    ")\n",
    "fig.text(\n",
    "    0.5, -0.04,\n",
    "    \"Brechas   Rendimiento: -1 | Seguridad: -3 \\u26a0 | Disponibilidad: -2 | \"\n",
    "    \"Escalabilidad: -1 | Mantenibilidad: -1 | Usabilidad: -1 | Precisi\\u00f3n Agro: -1\",\n",
    "    ha=\"center\", fontsize=8.5, color=\"#8b949e\", style=\"italic\"\n",
    ")\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig(\"radar_calidad_sistema.png\", dpi=150, bbox_inches=\"tight\",\n",
    "            facecolor=fig.get_facecolor())\n",
    "plt.show()\n",
    "print(\"Radar guardado en radar_calidad_sistema.png\")\n",
])

# Agregar al notebook
nb["cells"].extend([MD_14, CODE_14, MD_15, CODE_15])

with open(NB_PATH, "w", encoding="utf-8") as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print(f"OK — notebook ahora tiene {len(nb['cells'])} celdas")
print(f"Secciones 14 y 15 agregadas a: {NB_PATH}")
